"use client";

import { useState, useEffect } from "react";
import { usePathname } from "next/navigation";
import { Moon, Sun, Globe } from "lucide-react";

// Master dictionary for top Navbar and Parent DOM elements
const masterDict: Record<string, Record<string, string>> = {
  en: {
    "HOME": "HOME",
    "CURSOS": "COURSES",
    "TOOLS": "TOOLS",
    "DASHBOARD": "DASHBOARD",
    "Entrar": "Sign In",
    "Acesso Antecipado": "Early Access",
    "Acesso antecipado": "Early Access",
    "Painel do Aluno": "Student Dashboard",
    "Painel Admin": "Admin Panel",
    "Sair da conta": "Sign Out",
    "Pesquisar...": "Search...",
    "Minha Conta": "My Account",
    "Voltar": "Back",
    "Especialistas": "Specialists",
    "Evolua sua arte com inteligência artificial. Nossa ferramenta foi treinada exclusivamente com técnicas avançadas de tatuagem.": "Evolve your art with artificial intelligence. Our tool was trained exclusively on advanced tattoo techniques.",
    "Mais Vendido": "Best Seller",
    "Tutor IA Especialista": "Specialist AI Tutor",
    "Um mentor particular disponível 24h. Tire dúvidas técnicas em tempo real, receba sugestões precisas de agulhas e pigmentos para cada projeto, e tenha ajuda no planejamento completo das suas sessões.": "A private mentor available 24/7. Get technical questions answered in real time, receive precise needle and pigment suggestions for each project, and get help planning your sessions completely.",
    "Planejamento de Sessão": "Session Planning",
    "Análise de Pigmentos": "Pigment Analysis",
    "Mentoria Técnica 24h": "24/7 Technical Mentoring",
    "Gratuito": "Free",
    "Acessar Tutor": "Access Tutor",
    "Novo": "New",
    "Assistente WhatsApp": "WhatsApp Assistant",
    "Automatize seus orçamentos. A IA conversa com os clientes no WhatsApp, entende a ideia da tattoo e já sugere valores baseados na sua tabela.": "Automate your quotes. The AI talks to clients on WhatsApp, understands the tattoo idea, and already suggests prices based on your price table.",
    "Orçamentos Automáticos": "Automatic Quotes",
    "Agendamento de Horários": "Appointment Scheduling",
    "Triagem de Clientes 24h": "24/7 Client Screening",
    "/mês": "/month",
    "Assinar Assistente": "Subscribe to Assistant",
    "© 2026 Ink Authority. Todos os direitos reservados.": "© 2026 Ink Authority. All rights reserved.",
    "Desenvolvido para criadores e tatuadores profissionais.": "Built for professional creators and tattoo artists.",
    "O Primeiro Passo Para o Topo": "The First Step to the Top",
    "Posicionamento para": "Positioning for",
    "tatuadores": "tattoo artists",
    "Não basta ser o melhor tatuador se ninguém conhece o seu trabalho. Aprenda os segredos exatos para se posicionar como autoridade, atrair clientes que pagam caro e transformar sua arte num negócio altamente lucrativo.": "It's not enough to be the best tattoo artist if nobody knows your work. Learn the exact secrets to position yourself as an authority, attract clients who pay well, and turn your art into a highly profitable business.",
    "O que é posicionamento e como aplicá-lo à sua carreira artística": "What positioning is and how to apply it to your artistic career",
    "Estruturação das suas redes sociais": "Structuring your social media",
    "Criação de conteúdos que atraem clientes": "Creating content that attracts clients",
    "Técnicas de vendas e conversão de clientes": "Sales techniques and client conversion",
    "Como utilizar o tráfego pago de forma objetiva": "How to use paid traffic effectively",
    "Acesso à comunidade exclusiva da Ink Authority": "Access to the exclusive Ink Authority community",
    "🎁 BÔNUS: Análise de perfil grátis (para os 20 primeiros)": "🎁 BONUS: Free profile analysis (for the first 20)",
    "Investimento": "Investment",
    "Ou 12x de R$ 99,70": "Or 12x of R$99.70",
    "Processando...": "Processing...",
    "Garantir Vaga": "Secure Your Spot",
    "Acesso imediato após o pagamento": "Immediate access after payment",
    "Assista ao Vídeo": "Watch the Video",
    "Aumente o som": "Turn up the sound",
    "Menu": "Menu",
    "Meu Aprendizado": "My Learning",
    "Ao Vivo": "Live",
    "Comunidade": "Community",
    "Minhas Matérias": "My Courses",
    "Biblioteca": "Library",
    "Meu Perfil": "My Profile",
    "Perfil": "Profile",
    "Bem-vindo de volta,": "Welcome back,",
    "Acompanhe seu progresso de aprendizado na Ink Authority.": "Track your learning progress at Ink Authority.",
    "Meu Aprendizado em Andamento": "My Learning in Progress",
    "Carregando seu progresso...": "Loading your progress...",
    "Nenhum curso em andamento": "No courses in progress",
    "Seu progresso de estudo aparecerá aqui conforme você acessar e concluir as aulas das matérias disponíveis.": "Your study progress will appear here as you access and complete lessons from the available courses.",
    "Explorar Matérias Disponíveis": "Explore Available Courses",
    "Curso da metodologia Ink Authority.": "Ink Authority methodology course.",
    "Continuar Estudando": "Continue Studying",
    "Aulas ao Vivo": "Live Classes",
    "Assista as transmissões em tempo real e mentorias com a comunidade.": "Watch real-time broadcasts and mentoring sessions with the community.",
    "Carregando transmissões...": "Loading broadcasts...",
    "Nenhuma aula ao vivo agendada": "No live classes scheduled",
    "As transmissões ao vivo com a Isabela Badini e mentorias da comunidade aparecerão aqui assim que forem programadas.": "Live broadcasts with Isabela Badini and community mentoring sessions will appear here as soon as they're scheduled.",
    "Ao Vivo Agora": "Live Now",
    "Encerrada (Gravação)": "Ended (Recording)",
    "Nenhuma descrição disponível.": "No description available.",
    "Ferramentas de IA": "AI Tools",
    "Automatize seu estúdio com inteligência artificial treinada para tatuadores.": "Automate your studio with artificial intelligence trained for tattoo artists.",
    "Seu mentor particular 24 horas por dia. Nossa IA sugere agulhas, pigmentos e ajuda no planejamento cirúrgico.": "Your private mentor, 24 hours a day. Our AI suggests needles and pigments, and helps with precise session planning.",
    "Bate-papo Interativo": "Interactive Chat",
    "Avaliação de Trabalhos": "Work Assessment",
    "Automatize seus orçamentos. A IA conversa com os clientes no WhatsApp, entende a ideia da tattoo e cadastra o cliente direto na sua agenda.": "Automate your quotes. The AI chats with clients on WhatsApp, understands the tattoo idea, and adds the client straight to your schedule.",
    "Configurar Número": "Set Up Number",
    "Integração de Agenda": "Schedule Integration",
    "Acessar WhatsApp": "Access WhatsApp",
    "Matérias Disponíveis": "Available Courses",
    "Acesse seus treinamentos ou descubra novos conteúdos para evoluir sua arte.": "Access your training or discover new content to evolve your art.",
    "Carregando acervo...": "Loading collection...",
    "Nenhuma matéria disponível": "No courses available",
    "O administrador ainda não publicou nenhuma matéria.": "The admin hasn't published any courses yet.",
    "Acessar": "Access",
    "Bloqueado": "Locked",
    "Módulos": "Modules",
    "Desbloquear Matéria": "Unlock Course",
    "Acervo Oficial": "Official Collection",
    "Biblioteca Pro": "Pro Library",
    "Baixe materiais práticos, e-books, manuais e guias estratégicos exclusivos.": "Download practical materials, e-books, manuals, and exclusive strategic guides.",
    "Todos": "All",
    "Contratos": "Contracts",
    "Planilhas": "Spreadsheets",
    "Outros": "Others",
    "Nenhum material encontrado nesta categoria.": "No material found in this category.",
    "DOCUMENTO PDF": "PDF DOCUMENT",
    "Acesso Liberado": "Access Granted",
    "Baixar Documento PDF": "Download PDF Document",
    "Manual prático com diretrizes e templates prontos.": "Practical manual with guidelines and ready-made templates.",
    "Guia Prático: Instagram + ChatGPT para Tatuadores": "Practical Guide: Instagram + ChatGPT for Tattoo Artists",
    "Como utilizar Inteligência Artificial para gerar conteúdos de alto impacto, criar legendas persuasivas e atrair clientes diariamente no Instagram.": "How to use Artificial Intelligence to generate high-impact content, write persuasive captions, and attract clients daily on Instagram.",
    "DOCUMENTO EXCLUSIVO PRO": "EXCLUSIVE PRO DOCUMENT",
    "Gerencie sua conta, foto de perfil e informações de segurança.": "Manage your account, profile photo, and security information.",
    "Nome atualizado com sucesso!": "Name updated successfully!",
    "Foto atualizada com sucesso!": "Photo updated successfully!",
    "Salvar": "Save",
    "Cancelar": "Cancel",
    "Editar Perfil": "Edit Profile",
    "Endereços de Email": "Email Addresses",
    "Verificado · Principal": "Verified · Primary",
    "Segurança da Conta": "Account Security",
    "Senha": "Password",
    "Gerencie a proteção do seu acesso": "Manage the protection of your access",
    "Ativa": "Active",
    "Não configurada": "Not set up",
    "Autenticação em Duas Etapas": "Two-Factor Authentication",
    "Status de proteção da conta": "Account protection status",
    "Desativada": "Disabled",
    "Usuário": "User",
    "Comunidade Authority": "Authority Community",
    "Compartilhe resultados, tire dúvidas e faça networking com outros artistas.": "Share results, ask questions, and network with other artists.",
    "Faça login para publicar": "Log in to post",
    "Adicionar Foto": "Add Photo",
    "Enviando...": "Sending...",
    "Publicar": "Post",
    "Carregando feed...": "Loading feed...",
    "Nenhuma publicação ainda. Seja o primeiro a postar!": "No posts yet. Be the first to post!",
    "Editar Publicação": "Edit Post",
    "Apagar Publicação": "Delete Post",
    "Salvando...": "Saving...",
    "Curtidas": "Likes",
    "Comentários": "Comments",
    "Explorar a Plataforma": "Explore the Platform",
    "Assista transmissões e mentorias ao vivo com a comunidade.": "Watch live broadcasts and mentoring sessions with the community.",
    "Compartilhe resultados e conecte-se com outros artistas.": "Share results and connect with other artists.",
    "Tutor IA e assistente de WhatsApp para automatizar seu estúdio.": "AI Tutor and WhatsApp assistant to automate your studio.",
    "Explore as matérias disponíveis e continue seus estudos.": "Explore the available courses and continue your studies.",
    "Baixe materiais, e-books e guias exclusivos.": "Download exclusive materials, e-books, and guides.",
    "Gerencie sua conta e informações de segurança.": "Manage your account and security information."
  },
  es: {
    "HOME": "INICIO",
    "CURSOS": "CURSOS",
    "TOOLS": "HERRAMIENTAS",
    "DASHBOARD": "PANEL",
    "Entrar": "Iniciar Sesión",
    "Acesso Antecipado": "Acceso Anticipado",
    "Acesso antecipado": "Acceso anticipado",
    "Painel do Aluno": "Panel del Alumno",
    "Painel Admin": "Panel de Admin",
    "Sair da conta": "Cerrar sesión",
    "Pesquisar...": "Buscar...",
    "Minha Conta": "Mi Cuenta",
    "Voltar": "Volver",
    "Especialistas": "Especialistas",
    "Evolua sua arte com inteligência artificial. Nossa ferramenta foi treinada exclusivamente com técnicas avançadas de tatuagem.": "Evoluciona tu arte con inteligencia artificial. Nuestra herramienta fue entrenada exclusivamente con técnicas avanzadas de tatuaje.",
    "Mais Vendido": "Más Vendido",
    "Tutor IA Especialista": "Tutor IA Especialista",
    "Um mentor particular disponível 24h. Tire dúvidas técnicas em tempo real, receba sugestões precisas de agulhas e pigmentos para cada projeto, e tenha ajuda no planejamento completo das suas sessões.": "Un mentor particular disponible 24h. Resuelve dudas técnicas en tiempo real, recibe sugerencias precisas de agujas y pigmentos para cada proyecto, y ten ayuda en la planificación completa de tus sesiones.",
    "Planejamento de Sessão": "Planificación de Sesión",
    "Análise de Pigmentos": "Análisis de Pigmentos",
    "Mentoria Técnica 24h": "Mentoría Técnica 24h",
    "Gratuito": "Gratis",
    "Acessar Tutor": "Acceder al Tutor",
    "Novo": "Nuevo",
    "Assistente WhatsApp": "Asistente de WhatsApp",
    "Automatize seus orçamentos. A IA conversa com os clientes no WhatsApp, entende a ideia da tattoo e já sugere valores baseados na sua tabela.": "Automatiza tus presupuestos. La IA conversa con los clientes por WhatsApp, entiende la idea del tatuaje y ya sugiere valores según tu tabla.",
    "Orçamentos Automáticos": "Presupuestos Automáticos",
    "Agendamento de Horários": "Agenda de Horarios",
    "Triagem de Clientes 24h": "Filtrado de Clientes 24h",
    "/mês": "/mes",
    "Assinar Assistente": "Suscribirse al Asistente",
    "© 2026 Ink Authority. Todos os direitos reservados.": "© 2026 Ink Authority. Todos los derechos reservados.",
    "Desenvolvido para criadores e tatuadores profissionais.": "Desarrollado para creadores y tatuadores profesionales.",
    "O Primeiro Passo Para o Topo": "El Primer Paso Hacia la Cima",
    "Posicionamento para": "Posicionamiento para",
    "tatuadores": "tatuadores",
    "Não basta ser o melhor tatuador se ninguém conhece o seu trabalho. Aprenda os segredos exatos para se posicionar como autoridade, atrair clientes que pagam caro e transformar sua arte num negócio altamente lucrativo.": "No basta con ser el mejor tatuador si nadie conoce tu trabajo. Aprende los secretos exactos para posicionarte como autoridad, atraer clientes que pagan bien y transformar tu arte en un negocio muy rentable.",
    "O que é posicionamento e como aplicá-lo à sua carreira artística": "Qué es el posicionamiento y cómo aplicarlo a tu carrera artística",
    "Estruturação das suas redes sociais": "Estructuración de tus redes sociales",
    "Criação de conteúdos que atraem clientes": "Creación de contenidos que atraen clientes",
    "Técnicas de vendas e conversão de clientes": "Técnicas de ventas y conversión de clientes",
    "Como utilizar o tráfego pago de forma objetiva": "Cómo utilizar el tráfico pago de forma objetiva",
    "Acesso à comunidade exclusiva da Ink Authority": "Acceso a la comunidad exclusiva de Ink Authority",
    "🎁 BÔNUS: Análise de perfil grátis (para os 20 primeiros)": "🎁 BONO: Análisis de perfil gratis (para los primeros 20)",
    "Investimento": "Inversión",
    "Ou 12x de R$ 99,70": "O 12x de R$99,70",
    "Processando...": "Procesando...",
    "Garantir Vaga": "Asegurar mi Cupo",
    "Acesso imediato após o pagamento": "Acceso inmediato tras el pago",
    "Assista ao Vídeo": "Mira el Video",
    "Aumente o som": "Sube el volumen",
    "Menu": "Menú",
    "Meu Aprendizado": "Mi Aprendizaje",
    "Ao Vivo": "En Vivo",
    "Comunidade": "Comunidad",
    "Minhas Matérias": "Mis Materias",
    "Biblioteca": "Biblioteca",
    "Meu Perfil": "Mi Perfil",
    "Perfil": "Perfil",
    "Bem-vindo de volta,": "Bienvenido de nuevo,",
    "Acompanhe seu progresso de aprendizado na Ink Authority.": "Sigue tu progreso de aprendizaje en Ink Authority.",
    "Meu Aprendizado em Andamento": "Mi Aprendizaje en Curso",
    "Carregando seu progresso...": "Cargando tu progreso...",
    "Nenhum curso em andamento": "Ningún curso en curso",
    "Seu progresso de estudo aparecerá aqui conforme você acessar e concluir as aulas das matérias disponíveis.": "Tu progreso de estudio aparecerá aquí a medida que accedas y completes las clases de las materias disponibles.",
    "Explorar Matérias Disponíveis": "Explorar Materias Disponibles",
    "Curso da metodologia Ink Authority.": "Curso de la metodología Ink Authority.",
    "Continuar Estudando": "Continuar Estudiando",
    "Aulas ao Vivo": "Clases en Vivo",
    "Assista as transmissões em tempo real e mentorias com a comunidade.": "Mira las transmisiones en tiempo real y mentorías con la comunidad.",
    "Carregando transmissões...": "Cargando transmisiones...",
    "Nenhuma aula ao vivo agendada": "No hay clases en vivo programadas",
    "As transmissões ao vivo com a Isabela Badini e mentorias da comunidade aparecerão aqui assim que forem programadas.": "Las transmisiones en vivo con Isabela Badini y las mentorías de la comunidad aparecerán aquí en cuanto se programen.",
    "Ao Vivo Agora": "En Vivo Ahora",
    "Encerrada (Gravação)": "Finalizada (Grabación)",
    "Nenhuma descrição disponível.": "Ninguna descripción disponible.",
    "Ferramentas de IA": "Herramientas de IA",
    "Automatize seu estúdio com inteligência artificial treinada para tatuadores.": "Automatiza tu estudio con inteligencia artificial entrenada para tatuadores.",
    "Seu mentor particular 24 horas por dia. Nossa IA sugere agulhas, pigmentos e ajuda no planejamento cirúrgico.": "Tu mentor particular las 24 horas. Nuestra IA sugiere agujas y pigmentos, y ayuda en la planificación precisa de tus sesiones.",
    "Bate-papo Interativo": "Chat Interactivo",
    "Avaliação de Trabalhos": "Evaluación de Trabajos",
    "Automatize seus orçamentos. A IA conversa com os clientes no WhatsApp, entende a ideia da tattoo e cadastra o cliente direto na sua agenda.": "Automatiza tus presupuestos. La IA conversa con los clientes por WhatsApp, entiende la idea del tatuaje y registra al cliente directo en tu agenda.",
    "Configurar Número": "Configurar Número",
    "Integração de Agenda": "Integración de Agenda",
    "Acessar WhatsApp": "Acceder a WhatsApp",
    "Matérias Disponíveis": "Materias Disponibles",
    "Acesse seus treinamentos ou descubra novos conteúdos para evoluir sua arte.": "Accede a tus entrenamientos o descubre nuevos contenidos para evolucionar tu arte.",
    "Carregando acervo...": "Cargando acervo...",
    "Nenhuma matéria disponível": "Ninguna materia disponible",
    "O administrador ainda não publicou nenhuma matéria.": "El administrador aún no ha publicado ninguna materia.",
    "Acessar": "Acceder",
    "Bloqueado": "Bloqueado",
    "Módulos": "Módulos",
    "Desbloquear Matéria": "Desbloquear Materia",
    "Acervo Oficial": "Acervo Oficial",
    "Biblioteca Pro": "Biblioteca Pro",
    "Baixe materiais práticos, e-books, manuais e guias estratégicos exclusivos.": "Descarga materiales prácticos, e-books, manuales y guías estratégicas exclusivas.",
    "Todos": "Todos",
    "Contratos": "Contratos",
    "Planilhas": "Hojas de Cálculo",
    "Outros": "Otros",
    "Nenhum material encontrado nesta categoria.": "No se encontró ningún material en esta categoría.",
    "DOCUMENTO PDF": "DOCUMENTO PDF",
    "Acesso Liberado": "Acceso Liberado",
    "Baixar Documento PDF": "Descargar Documento PDF",
    "Manual prático com diretrizes e templates prontos.": "Manual práctico con directrices y plantillas listas.",
    "Guia Prático: Instagram + ChatGPT para Tatuadores": "Guía Práctica: Instagram + ChatGPT para Tatuadores",
    "Como utilizar Inteligência Artificial para gerar conteúdos de alto impacto, criar legendas persuasivas e atrair clientes diariamente no Instagram.": "Cómo utilizar Inteligencia Artificial para generar contenidos de alto impacto, crear leyendas persuasivas y atraer clientes a diario en Instagram.",
    "DOCUMENTO EXCLUSIVO PRO": "DOCUMENTO EXCLUSIVO PRO",
    "Gerencie sua conta, foto de perfil e informações de segurança.": "Gestiona tu cuenta, foto de perfil e información de seguridad.",
    "Nome atualizado com sucesso!": "¡Nombre actualizado con éxito!",
    "Foto atualizada com sucesso!": "¡Foto actualizada con éxito!",
    "Salvar": "Guardar",
    "Cancelar": "Cancelar",
    "Editar Perfil": "Editar Perfil",
    "Endereços de Email": "Direcciones de Correo",
    "Verificado · Principal": "Verificado · Principal",
    "Segurança da Conta": "Seguridad de la Cuenta",
    "Senha": "Contraseña",
    "Gerencie a proteção do seu acesso": "Gestiona la protección de tu acceso",
    "Ativa": "Activa",
    "Não configurada": "No configurada",
    "Autenticação em Duas Etapas": "Autenticación en Dos Pasos",
    "Status de proteção da conta": "Estado de protección de la cuenta",
    "Desativada": "Desactivada",
    "Usuário": "Usuario",
    "Comunidade Authority": "Comunidad Authority",
    "Compartilhe resultados, tire dúvidas e faça networking com outros artistas.": "Comparte resultados, resuelve dudas y haz networking con otros artistas.",
    "Faça login para publicar": "Inicia sesión para publicar",
    "Adicionar Foto": "Añadir Foto",
    "Enviando...": "Enviando...",
    "Publicar": "Publicar",
    "Carregando feed...": "Cargando feed...",
    "Nenhuma publicação ainda. Seja o primeiro a postar!": "Aún no hay publicaciones. ¡Sé el primero en publicar!",
    "Editar Publicação": "Editar Publicación",
    "Apagar Publicação": "Eliminar Publicación",
    "Salvando...": "Guardando...",
    "Curtidas": "Me Gusta",
    "Comentários": "Comentarios",
    "Explorar a Plataforma": "Explorar la Plataforma",
    "Assista transmissões e mentorias ao vivo com a comunidade.": "Mira transmisiones y mentorías en vivo con la comunidad.",
    "Compartilhe resultados e conecte-se com outros artistas.": "Comparte resultados y conéctate con otros artistas.",
    "Tutor IA e assistente de WhatsApp para automatizar seu estúdio.": "Tutor IA y asistente de WhatsApp para automatizar tu estudio.",
    "Explore as matérias disponíveis e continue seus estudos.": "Explora las materias disponibles y continúa tus estudios.",
    "Baixe materiais, e-books e guias exclusivos.": "Descarga materiales, e-books y guías exclusivas.",
    "Gerencie sua conta e informações de segurança.": "Gestiona tu cuenta e información de seguridad."
  },
  fr: {
    "HOME": "ACCUEIL",
    "CURSOS": "COURS",
    "TOOLS": "OUTILS",
    "DASHBOARD": "TABLEAU DE BORD",
    "Entrar": "Se Connecter",
    "Acesso Antecipado": "Accès Anticipé",
    "Acesso antecipado": "Accès anticipé",
    "Painel do Aluno": "Espace Étudiant",
    "Painel Admin": "Panneau Admin",
    "Sair da conta": "Se Déconnecter",
    "Pesquisar...": "Rechercher...",
    "Minha Conta": "Mon Compte",
    "Voltar": "Retour",
    "Especialistas": "Spécialistes",
    "Evolua sua arte com inteligência artificial. Nossa ferramenta foi treinada exclusivamente com técnicas avançadas de tatuagem.": "Faites évoluer votre art avec l'intelligence artificielle. Notre outil a été entraîné exclusivement sur des techniques avancées de tatouage.",
    "Mais Vendido": "Meilleure Vente",
    "Tutor IA Especialista": "Tuteur IA Spécialiste",
    "Um mentor particular disponível 24h. Tire dúvidas técnicas em tempo real, receba sugestões precisas de agulhas e pigmentos para cada projeto, e tenha ajuda no planejamento completo das suas sessões.": "Un mentor privé disponible 24h/24. Posez vos questions techniques en temps réel, recevez des suggestions précises d'aiguilles et de pigments pour chaque projet, et obtenez de l'aide pour planifier entièrement vos séances.",
    "Planejamento de Sessão": "Planification de Séance",
    "Análise de Pigmentos": "Analyse des Pigments",
    "Mentoria Técnica 24h": "Mentorat Technique 24h/24",
    "Gratuito": "Gratuit",
    "Acessar Tutor": "Accéder au Tuteur",
    "Novo": "Nouveau",
    "Assistente WhatsApp": "Assistant WhatsApp",
    "Automatize seus orçamentos. A IA conversa com os clientes no WhatsApp, entende a ideia da tattoo e já sugere valores baseados na sua tabela.": "Automatisez vos devis. L'IA discute avec les clients sur WhatsApp, comprend l'idée du tatouage et suggère déjà des prix selon votre grille tarifaire.",
    "Orçamentos Automáticos": "Devis Automatiques",
    "Agendamento de Horários": "Prise de Rendez-vous",
    "Triagem de Clientes 24h": "Tri des Clients 24h/24",
    "/mês": "/mois",
    "Assinar Assistente": "S'abonner à l'Assistant",
    "© 2026 Ink Authority. Todos os direitos reservados.": "© 2026 Ink Authority. Tous droits réservés.",
    "Desenvolvido para criadores e tatuadores profissionais.": "Conçu pour les créateurs et tatoueurs professionnels.",
    "O Primeiro Passo Para o Topo": "Le Premier Pas Vers le Sommet",
    "Posicionamento para": "Positionnement pour",
    "tatuadores": "tatoueurs",
    "Não basta ser o melhor tatuador se ninguém conhece o seu trabalho. Aprenda os segredos exatos para se posicionar como autoridade, atrair clientes que pagam caro e transformar sua arte num negócio altamente lucrativo.": "Il ne suffit pas d'être le meilleur tatoueur si personne ne connaît votre travail. Apprenez les secrets exacts pour vous positionner en tant qu'autorité, attirer des clients qui paient bien et transformer votre art en une activité très rentable.",
    "O que é posicionamento e como aplicá-lo à sua carreira artística": "Qu'est-ce que le positionnement et comment l'appliquer à votre carrière artistique",
    "Estruturação das suas redes sociais": "Structuration de vos réseaux sociaux",
    "Criação de conteúdos que atraem clientes": "Création de contenus qui attirent des clients",
    "Técnicas de vendas e conversão de clientes": "Techniques de vente et de conversion de clients",
    "Como utilizar o tráfego pago de forma objetiva": "Comment utiliser le trafic payant de manière efficace",
    "Acesso à comunidade exclusiva da Ink Authority": "Accès à la communauté exclusive d'Ink Authority",
    "🎁 BÔNUS: Análise de perfil grátis (para os 20 primeiros)": "🎁 BONUS : Analyse de profil gratuite (pour les 20 premiers)",
    "Investimento": "Investissement",
    "Ou 12x de R$ 99,70": "Ou 12x de 99,70 R$",
    "Processando...": "Traitement en cours...",
    "Garantir Vaga": "Réserver ma Place",
    "Acesso imediato após o pagamento": "Accès immédiat après le paiement",
    "Assista ao Vídeo": "Regarder la Vidéo",
    "Aumente o som": "Augmentez le son",
    "Menu": "Menu",
    "Meu Aprendizado": "Mon Apprentissage",
    "Ao Vivo": "En Direct",
    "Comunidade": "Communauté",
    "Minhas Matérias": "Mes Cours",
    "Biblioteca": "Bibliothèque",
    "Meu Perfil": "Mon Profil",
    "Perfil": "Profil",
    "Bem-vindo de volta,": "Bon retour,",
    "Acompanhe seu progresso de aprendizado na Ink Authority.": "Suivez votre progression d'apprentissage sur Ink Authority.",
    "Meu Aprendizado em Andamento": "Mon Apprentissage en Cours",
    "Carregando seu progresso...": "Chargement de votre progression...",
    "Nenhum curso em andamento": "Aucun cours en cours",
    "Seu progresso de estudo aparecerá aqui conforme você acessar e concluir as aulas das matérias disponíveis.": "Votre progression apparaîtra ici au fur et à mesure que vous accédez et terminez les leçons des cours disponibles.",
    "Explorar Matérias Disponíveis": "Explorer les Cours Disponibles",
    "Curso da metodologia Ink Authority.": "Cours de la méthodologie Ink Authority.",
    "Continuar Estudando": "Continuer à Étudier",
    "Aulas ao Vivo": "Cours en Direct",
    "Assista as transmissões em tempo real e mentorias com a comunidade.": "Regardez les diffusions en temps réel et les mentorats avec la communauté.",
    "Carregando transmissões...": "Chargement des diffusions...",
    "Nenhuma aula ao vivo agendada": "Aucun cours en direct programmé",
    "As transmissões ao vivo com a Isabela Badini e mentorias da comunidade aparecerão aqui assim que forem programadas.": "Les diffusions en direct avec Isabela Badini et les mentorats de la communauté apparaîtront ici dès qu'ils seront programmés.",
    "Ao Vivo Agora": "En Direct Maintenant",
    "Encerrada (Gravação)": "Terminée (Enregistrement)",
    "Nenhuma descrição disponível.": "Aucune description disponible.",
    "Ferramentas de IA": "Outils d'IA",
    "Automatize seu estúdio com inteligência artificial treinada para tatuadores.": "Automatisez votre studio avec une intelligence artificielle formée pour les tatoueurs.",
    "Seu mentor particular 24 horas por dia. Nossa IA sugere agulhas, pigmentos e ajuda no planejamento cirúrgico.": "Votre mentor privé 24 heures sur 24. Notre IA suggère des aiguilles et des pigments, et aide à planifier précisément vos séances.",
    "Bate-papo Interativo": "Chat Interactif",
    "Avaliação de Trabalhos": "Évaluation des Travaux",
    "Automatize seus orçamentos. A IA conversa com os clientes no WhatsApp, entende a ideia da tattoo e cadastra o cliente direto na sua agenda.": "Automatisez vos devis. L'IA discute avec les clients sur WhatsApp, comprend l'idée du tatouage et ajoute le client directement dans votre agenda.",
    "Configurar Número": "Configurer le Numéro",
    "Integração de Agenda": "Intégration de l'Agenda",
    "Acessar WhatsApp": "Accéder à WhatsApp",
    "Matérias Disponíveis": "Cours Disponibles",
    "Acesse seus treinamentos ou descubra novos conteúdos para evoluir sua arte.": "Accédez à vos formations ou découvrez de nouveaux contenus pour faire évoluer votre art.",
    "Carregando acervo...": "Chargement de la collection...",
    "Nenhuma matéria disponível": "Aucun cours disponible",
    "O administrador ainda não publicou nenhuma matéria.": "L'administrateur n'a encore publié aucun cours.",
    "Acessar": "Accéder",
    "Bloqueado": "Verrouillé",
    "Módulos": "Modules",
    "Desbloquear Matéria": "Débloquer le Cours",
    "Acervo Oficial": "Collection Officielle",
    "Biblioteca Pro": "Bibliothèque Pro",
    "Baixe materiais práticos, e-books, manuais e guias estratégicos exclusivos.": "Téléchargez des supports pratiques, e-books, manuels et guides stratégiques exclusifs.",
    "Todos": "Tous",
    "Contratos": "Contrats",
    "Planilhas": "Feuilles de Calcul",
    "Outros": "Autres",
    "Nenhum material encontrado nesta categoria.": "Aucun support trouvé dans cette catégorie.",
    "DOCUMENTO PDF": "DOCUMENT PDF",
    "Acesso Liberado": "Accès Débloqué",
    "Baixar Documento PDF": "Télécharger le Document PDF",
    "Manual prático com diretrizes e templates prontos.": "Manuel pratique avec directives et modèles prêts à l'emploi.",
    "Guia Prático: Instagram + ChatGPT para Tatuadores": "Guide Pratique : Instagram + ChatGPT pour Tatoueurs",
    "Como utilizar Inteligência Artificial para gerar conteúdos de alto impacto, criar legendas persuasivas e atrair clientes diariamente no Instagram.": "Comment utiliser l'Intelligence Artificielle pour générer du contenu à fort impact, créer des légendes persuasives et attirer des clients chaque jour sur Instagram.",
    "DOCUMENTO EXCLUSIVO PRO": "DOCUMENT EXCLUSIF PRO",
    "Gerencie sua conta, foto de perfil e informações de segurança.": "Gérez votre compte, votre photo de profil et vos informations de sécurité.",
    "Nome atualizado com sucesso!": "Nom mis à jour avec succès !",
    "Foto atualizada com sucesso!": "Photo mise à jour avec succès !",
    "Salvar": "Enregistrer",
    "Cancelar": "Annuler",
    "Editar Perfil": "Modifier le Profil",
    "Endereços de Email": "Adresses E-mail",
    "Verificado · Principal": "Vérifié · Principal",
    "Segurança da Conta": "Sécurité du Compte",
    "Senha": "Mot de Passe",
    "Gerencie a proteção do seu acesso": "Gérez la protection de votre accès",
    "Ativa": "Active",
    "Não configurada": "Non configurée",
    "Autenticação em Duas Etapas": "Authentification à Deux Facteurs",
    "Status de proteção da conta": "Statut de protection du compte",
    "Desativada": "Désactivée",
    "Usuário": "Utilisateur",
    "Comunidade Authority": "Communauté Authority",
    "Compartilhe resultados, tire dúvidas e faça networking com outros artistas.": "Partagez vos résultats, posez vos questions et réseautez avec d'autres artistes.",
    "Faça login para publicar": "Connectez-vous pour publier",
    "Adicionar Foto": "Ajouter une Photo",
    "Enviando...": "Envoi en cours...",
    "Publicar": "Publier",
    "Carregando feed...": "Chargement du fil...",
    "Nenhuma publicação ainda. Seja o primeiro a postar!": "Aucune publication pour l'instant. Soyez le premier à publier !",
    "Editar Publicação": "Modifier la Publication",
    "Apagar Publicação": "Supprimer la Publication",
    "Salvando...": "Enregistrement...",
    "Curtidas": "J'aime",
    "Comentários": "Commentaires",
    "Explorar a Plataforma": "Explorer la Plateforme",
    "Assista transmissões e mentorias ao vivo com a comunidade.": "Regardez des diffusions et des mentorats en direct avec la communauté.",
    "Compartilhe resultados e conecte-se com outros artistas.": "Partagez vos résultats et connectez-vous avec d'autres artistes.",
    "Tutor IA e assistente de WhatsApp para automatizar seu estúdio.": "Tuteur IA et assistant WhatsApp pour automatiser votre studio.",
    "Explore as matérias disponíveis e continue seus estudos.": "Explorez les cours disponibles et poursuivez vos études.",
    "Baixe materiais, e-books e guias exclusivos.": "Téléchargez des supports, e-books et guides exclusifs.",
    "Gerencie sua conta e informações de segurança.": "Gérez votre compte et vos informations de sécurité."
  },
  de: {
    "HOME": "START",
    "CURSOS": "KURSE",
    "TOOLS": "WERKZEUGE",
    "DASHBOARD": "DASHBOARD",
    "Entrar": "Anmelden",
    "Acesso Antecipado": "Frühzeitiger Zugang",
    "Acesso antecipado": "Frühzeitiger Zugang",
    "Painel do Aluno": "Studenten-Dashboard",
    "Painel Admin": "Admin-Bereich",
    "Sair da conta": "Abmelden",
    "Pesquisar...": "Suchen...",
    "Minha Conta": "Mein Konto",
    "Voltar": "Zurück",
    "Especialistas": "Spezialisten",
    "Evolua sua arte com inteligência artificial. Nossa ferramenta foi treinada exclusivamente com técnicas avançadas de tatuagem.": "Entwickle deine Kunst mit künstlicher Intelligenz weiter. Unser Tool wurde ausschließlich mit fortgeschrittenen Tätowiertechniken trainiert.",
    "Mais Vendido": "Bestseller",
    "Tutor IA Especialista": "KI-Fachtutor",
    "Um mentor particular disponível 24h. Tire dúvidas técnicas em tempo real, receba sugestões precisas de agulhas e pigmentos para cada projeto, e tenha ajuda no planejamento completo das suas sessões.": "Ein privater Mentor, 24 Stunden verfügbar. Kläre technische Fragen in Echtzeit, erhalte präzise Nadel- und Pigmentempfehlungen für jedes Projekt und Hilfe bei der vollständigen Planung deiner Sitzungen.",
    "Planejamento de Sessão": "Sitzungsplanung",
    "Análise de Pigmentos": "Pigmentanalyse",
    "Mentoria Técnica 24h": "Technisches Mentoring 24h",
    "Gratuito": "Kostenlos",
    "Acessar Tutor": "Tutor öffnen",
    "Novo": "Neu",
    "Assistente WhatsApp": "WhatsApp-Assistent",
    "Automatize seus orçamentos. A IA conversa com os clientes no WhatsApp, entende a ideia da tattoo e já sugere valores baseados na sua tabela.": "Automatisiere deine Kostenvoranschläge. Die KI unterhält sich mit Kunden auf WhatsApp, versteht die Tattoo-Idee und schlägt bereits Preise basierend auf deiner Preistabelle vor.",
    "Orçamentos Automáticos": "Automatische Kostenvoranschläge",
    "Agendamento de Horários": "Terminplanung",
    "Triagem de Clientes 24h": "Kundenvorqualifizierung 24h",
    "/mês": "/Monat",
    "Assinar Assistente": "Assistent abonnieren",
    "© 2026 Ink Authority. Todos os direitos reservados.": "© 2026 Ink Authority. Alle Rechte vorbehalten.",
    "Desenvolvido para criadores e tatuadores profissionais.": "Entwickelt für professionelle Creator und Tätowierer.",
    "O Primeiro Passo Para o Topo": "Der Erste Schritt an die Spitze",
    "Posicionamento para": "Positionierung für",
    "tatuadores": "Tätowierer",
    "Não basta ser o melhor tatuador se ninguém conhece o seu trabalho. Aprenda os segredos exatos para se posicionar como autoridade, atrair clientes que pagam caro e transformar sua arte num negócio altamente lucrativo.": "Es reicht nicht, der beste Tätowierer zu sein, wenn niemand deine Arbeit kennt. Lerne die genauen Geheimnisse, um dich als Autorität zu positionieren, gut zahlende Kunden zu gewinnen und deine Kunst in ein hochprofitables Geschäft zu verwandeln.",
    "O que é posicionamento e como aplicá-lo à sua carreira artística": "Was Positionierung ist und wie du sie auf deine künstlerische Karriere anwendest",
    "Estruturação das suas redes sociais": "Strukturierung deiner sozialen Netzwerke",
    "Criação de conteúdos que atraem clientes": "Erstellung von Inhalten, die Kunden anziehen",
    "Técnicas de vendas e conversão de clientes": "Verkaufstechniken und Kundenkonversion",
    "Como utilizar o tráfego pago de forma objetiva": "Wie man bezahlten Traffic gezielt einsetzt",
    "Acesso à comunidade exclusiva da Ink Authority": "Zugang zur exklusiven Ink Authority-Community",
    "🎁 BÔNUS: Análise de perfil grátis (para os 20 primeiros)": "🎁 BONUS: Kostenlose Profilanalyse (für die ersten 20)",
    "Investimento": "Investition",
    "Ou 12x de R$ 99,70": "Oder 12x R$99,70",
    "Processando...": "Wird verarbeitet...",
    "Garantir Vaga": "Platz sichern",
    "Acesso imediato após o pagamento": "Sofortiger Zugang nach der Zahlung",
    "Assista ao Vídeo": "Video ansehen",
    "Aumente o som": "Ton lauter stellen",
    "Menu": "Menü",
    "Meu Aprendizado": "Mein Lernbereich",
    "Ao Vivo": "Live",
    "Comunidade": "Community",
    "Minhas Matérias": "Meine Kurse",
    "Biblioteca": "Bibliothek",
    "Meu Perfil": "Mein Profil",
    "Perfil": "Profil",
    "Bem-vindo de volta,": "Willkommen zurück,",
    "Acompanhe seu progresso de aprendizado na Ink Authority.": "Verfolge deinen Lernfortschritt bei Ink Authority.",
    "Meu Aprendizado em Andamento": "Mein Laufender Lernfortschritt",
    "Carregando seu progresso...": "Lade deinen Fortschritt...",
    "Nenhum curso em andamento": "Kein Kurs in Bearbeitung",
    "Seu progresso de estudo aparecerá aqui conforme você acessar e concluir as aulas das matérias disponíveis.": "Dein Lernfortschritt wird hier angezeigt, sobald du auf die verfügbaren Kurse zugreifst und die Lektionen abschließt.",
    "Explorar Matérias Disponíveis": "Verfügbare Kurse Entdecken",
    "Curso da metodologia Ink Authority.": "Kurs der Ink-Authority-Methodik.",
    "Continuar Estudando": "Weiter Lernen",
    "Aulas ao Vivo": "Live-Unterricht",
    "Assista as transmissões em tempo real e mentorias com a comunidade.": "Sieh dir Live-Übertragungen und Mentoring-Sitzungen mit der Community an.",
    "Carregando transmissões...": "Lade Übertragungen...",
    "Nenhuma aula ao vivo agendada": "Kein Live-Unterricht geplant",
    "As transmissões ao vivo com a Isabela Badini e mentorias da comunidade aparecerão aqui assim que forem programadas.": "Live-Übertragungen mit Isabela Badini und Community-Mentoring werden hier angezeigt, sobald sie geplant sind.",
    "Ao Vivo Agora": "Jetzt Live",
    "Encerrada (Gravação)": "Beendet (Aufzeichnung)",
    "Nenhuma descrição disponível.": "Keine Beschreibung verfügbar.",
    "Ferramentas de IA": "KI-Werkzeuge",
    "Automatize seu estúdio com inteligência artificial treinada para tatuadores.": "Automatisiere dein Studio mit künstlicher Intelligenz, die speziell für Tätowierer trainiert wurde.",
    "Seu mentor particular 24 horas por dia. Nossa IA sugere agulhas, pigmentos e ajuda no planejamento cirúrgico.": "Dein persönlicher Mentor, rund um die Uhr. Unsere KI schlägt Nadeln und Pigmente vor und hilft bei der präzisen Planung deiner Sitzungen.",
    "Bate-papo Interativo": "Interaktiver Chat",
    "Avaliação de Trabalhos": "Arbeitsbewertung",
    "Automatize seus orçamentos. A IA conversa com os clientes no WhatsApp, entende a ideia da tattoo e cadastra o cliente direto na sua agenda.": "Automatisiere deine Angebote. Die KI chattet mit Kunden auf WhatsApp, versteht die Tattoo-Idee und trägt den Kunden direkt in deinen Terminkalender ein.",
    "Configurar Número": "Nummer Einrichten",
    "Integração de Agenda": "Kalenderintegration",
    "Acessar WhatsApp": "WhatsApp Öffnen",
    "Matérias Disponíveis": "Verfügbare Kurse",
    "Acesse seus treinamentos ou descubra novos conteúdos para evoluir sua arte.": "Greife auf deine Schulungen zu oder entdecke neue Inhalte, um deine Kunst weiterzuentwickeln.",
    "Carregando acervo...": "Lade Sammlung...",
    "Nenhuma matéria disponível": "Kein Kurs verfügbar",
    "O administrador ainda não publicou nenhuma matéria.": "Der Administrator hat noch keinen Kurs veröffentlicht.",
    "Acessar": "Öffnen",
    "Bloqueado": "Gesperrt",
    "Módulos": "Module",
    "Desbloquear Matéria": "Kurs Freischalten",
    "Acervo Oficial": "Offizielle Sammlung",
    "Biblioteca Pro": "Pro-Bibliothek",
    "Baixe materiais práticos, e-books, manuais e guias estratégicos exclusivos.": "Lade praktische Materialien, E-Books, Handbücher und exklusive Strategie-Guides herunter.",
    "Todos": "Alle",
    "Contratos": "Verträge",
    "Planilhas": "Tabellen",
    "Outros": "Sonstiges",
    "Nenhum material encontrado nesta categoria.": "In dieser Kategorie wurde kein Material gefunden.",
    "DOCUMENTO PDF": "PDF-DOKUMENT",
    "Acesso Liberado": "Zugriff Freigeschaltet",
    "Baixar Documento PDF": "PDF-Dokument Herunterladen",
    "Manual prático com diretrizes e templates prontos.": "Praktisches Handbuch mit Richtlinien und fertigen Vorlagen.",
    "Guia Prático: Instagram + ChatGPT para Tatuadores": "Praktischer Leitfaden: Instagram + ChatGPT für Tätowierer",
    "Como utilizar Inteligência Artificial para gerar conteúdos de alto impacto, criar legendas persuasivas e atrair clientes diariamente no Instagram.": "Wie du künstliche Intelligenz nutzt, um wirkungsvolle Inhalte zu erstellen, überzeugende Bildunterschriften zu schreiben und täglich neue Kunden auf Instagram zu gewinnen.",
    "DOCUMENTO EXCLUSIVO PRO": "EXKLUSIVES PRO-DOKUMENT",
    "Gerencie sua conta, foto de perfil e informações de segurança.": "Verwalte dein Konto, Profilbild und deine Sicherheitsinformationen.",
    "Nome atualizado com sucesso!": "Name erfolgreich aktualisiert!",
    "Foto atualizada com sucesso!": "Foto erfolgreich aktualisiert!",
    "Salvar": "Speichern",
    "Cancelar": "Abbrechen",
    "Editar Perfil": "Profil Bearbeiten",
    "Endereços de Email": "E-Mail-Adressen",
    "Verificado · Principal": "Bestätigt · Primär",
    "Segurança da Conta": "Kontosicherheit",
    "Senha": "Passwort",
    "Gerencie a proteção do seu acesso": "Verwalte den Schutz deines Zugangs",
    "Ativa": "Aktiv",
    "Não configurada": "Nicht eingerichtet",
    "Autenticação em Duas Etapas": "Zwei-Faktor-Authentifizierung",
    "Status de proteção da conta": "Schutzstatus des Kontos",
    "Desativada": "Deaktiviert",
    "Usuário": "Benutzer",
    "Comunidade Authority": "Authority-Community",
    "Compartilhe resultados, tire dúvidas e faça networking com outros artistas.": "Teile Ergebnisse, stelle Fragen und vernetze dich mit anderen Künstlern.",
    "Faça login para publicar": "Melde dich an, um zu posten",
    "Adicionar Foto": "Foto Hinzufügen",
    "Enviando...": "Wird gesendet...",
    "Publicar": "Veröffentlichen",
    "Carregando feed...": "Lade Feed...",
    "Nenhuma publicação ainda. Seja o primeiro a postar!": "Noch keine Beiträge. Sei der Erste, der postet!",
    "Editar Publicação": "Beitrag Bearbeiten",
    "Apagar Publicação": "Beitrag Löschen",
    "Salvando...": "Wird gespeichert...",
    "Curtidas": "Gefällt mir",
    "Comentários": "Kommentare",
    "Explorar a Plataforma": "Plattform Entdecken",
    "Assista transmissões e mentorias ao vivo com a comunidade.": "Sieh dir Live-Übertragungen und Mentoring mit der Community an.",
    "Compartilhe resultados e conecte-se com outros artistas.": "Teile Ergebnisse und vernetze dich mit anderen Künstlern.",
    "Tutor IA e assistente de WhatsApp para automatizar seu estúdio.": "KI-Tutor und WhatsApp-Assistent, um dein Studio zu automatisieren.",
    "Explore as matérias disponíveis e continue seus estudos.": "Entdecke die verfügbaren Kurse und setze dein Lernen fort.",
    "Baixe materiais, e-books e guias exclusivos.": "Lade exklusive Materialien, E-Books und Guides herunter.",
    "Gerencie sua conta e informações de segurança.": "Verwalte dein Konto und deine Sicherheitsinformationen."
  },
  it: {
    "HOME": "HOME",
    "CURSOS": "CORSI",
    "TOOLS": "STRUMENTI",
    "DASHBOARD": "DASHBOARD",
    "Entrar": "Accedi",
    "Acesso Antecipado": "Accesso Anticipado",
    "Acesso antecipado": "Accesso anticipado",
    "Painel do Aluno": "Pannello Studente",
    "Painel Admin": "Pannello Admin",
    "Sair da conta": "Disconnetti",
    "Pesquisar...": "Cerca...",
    "Minha Conta": "Il Mio Account",
    "Voltar": "Indietro",
    "Especialistas": "Specialisti",
    "Evolua sua arte com inteligência artificial. Nossa ferramenta foi treinada exclusivamente com técnicas avançadas de tatuagem.": "Fai evolvere la tua arte con l'intelligenza artificiale. Il nostro strumento è stato addestrato esclusivamente con tecniche avanzate di tatuaggio.",
    "Mais Vendido": "Più Venduto",
    "Tutor IA Especialista": "Tutor IA Specialista",
    "Um mentor particular disponível 24h. Tire dúvidas técnicas em tempo real, receba sugestões precisas de agulhas e pigmentos para cada projeto, e tenha ajuda no planejamento completo das suas sessões.": "Un mentore privato disponibile 24 ore su 24. Risolvi dubbi tecnici in tempo reale, ricevi suggerimenti precisi su aghi e pigmenti per ogni progetto e ottieni aiuto nella pianificazione completa delle tue sessioni.",
    "Planejamento de Sessão": "Pianificazione della Sessione",
    "Análise de Pigmentos": "Analisi dei Pigmenti",
    "Mentoria Técnica 24h": "Mentoring Tecnico 24h",
    "Gratuito": "Gratuito",
    "Acessar Tutor": "Accedi al Tutor",
    "Novo": "Nuovo",
    "Assistente WhatsApp": "Assistente WhatsApp",
    "Automatize seus orçamentos. A IA conversa com os clientes no WhatsApp, entende a ideia da tattoo e já sugere valores baseados na sua tabela.": "Automatizza i tuoi preventivi. L'IA conversa con i clienti su WhatsApp, capisce l'idea del tatuaggio e suggerisce già i prezzi in base al tuo listino.",
    "Orçamentos Automáticos": "Preventivi Automatici",
    "Agendamento de Horários": "Pianificazione degli Appuntamenti",
    "Triagem de Clientes 24h": "Screening dei Clienti 24h",
    "/mês": "/mese",
    "Assinar Assistente": "Abbonati all'Assistente",
    "© 2026 Ink Authority. Todos os direitos reservados.": "© 2026 Ink Authority. Tutti i diritti riservati.",
    "Desenvolvido para criadores e tatuadores profissionais.": "Sviluppato per creator e tatuatori professionisti.",
    "O Primeiro Passo Para o Topo": "Il Primo Passo Verso il Vertice",
    "Posicionamento para": "Posizionamento per",
    "tatuadores": "tatuatori",
    "Não basta ser o melhor tatuador se ninguém conhece o seu trabalho. Aprenda os segredos exatos para se posicionar como autoridade, atrair clientes que pagam caro e transformar sua arte num negócio altamente lucrativo.": "Non basta essere il miglior tatuatore se nessuno conosce il tuo lavoro. Impara i segreti esatti per posizionarti come autorità, attrarre clienti che pagano bene e trasformare la tua arte in un business altamente redditizio.",
    "O que é posicionamento e como aplicá-lo à sua carreira artística": "Cos'è il posizionamento e come applicarlo alla tua carriera artistica",
    "Estruturação das suas redes sociais": "Strutturazione dei tuoi social media",
    "Criação de conteúdos que atraem clientes": "Creazione di contenuti che attirano clienti",
    "Técnicas de vendas e conversão de clientes": "Tecniche di vendita e conversione dei clienti",
    "Como utilizar o tráfego pago de forma objetiva": "Come utilizzare il traffico a pagamento in modo efficace",
    "Acesso à comunidade exclusiva da Ink Authority": "Accesso alla community esclusiva di Ink Authority",
    "🎁 BÔNUS: Análise de perfil grátis (para os 20 primeiros)": "🎁 BONUS: Analisi del profilo gratuita (per i primi 20)",
    "Investimento": "Investimento",
    "Ou 12x de R$ 99,70": "O 12x da R$99,70",
    "Processando...": "Elaborazione...",
    "Garantir Vaga": "Prenota il Tuo Posto",
    "Acesso imediato após o pagamento": "Accesso immediato dopo il pagamento",
    "Assista ao Vídeo": "Guarda il Video",
    "Aumente o som": "Alza il volume",
    "Menu": "Menu",
    "Meu Aprendizado": "Il Mio Apprendimento",
    "Ao Vivo": "Live",
    "Comunidade": "Comunità",
    "Minhas Matérias": "I Miei Corsi",
    "Biblioteca": "Biblioteca",
    "Meu Perfil": "Il Mio Profilo",
    "Perfil": "Profilo",
    "Bem-vindo de volta,": "Bentornato,",
    "Acompanhe seu progresso de aprendizado na Ink Authority.": "Segui i tuoi progressi di apprendimento su Ink Authority.",
    "Meu Aprendizado em Andamento": "Il Mio Apprendimento in Corso",
    "Carregando seu progresso...": "Caricamento dei tuoi progressi...",
    "Nenhum curso em andamento": "Nessun corso in corso",
    "Seu progresso de estudo aparecerá aqui conforme você acessar e concluir as aulas das matérias disponíveis.": "I tuoi progressi appariranno qui man mano che accedi e completi le lezioni dei corsi disponibili.",
    "Explorar Matérias Disponíveis": "Esplora i Corsi Disponibili",
    "Curso da metodologia Ink Authority.": "Corso della metodologia Ink Authority.",
    "Continuar Estudando": "Continua a Studiare",
    "Aulas ao Vivo": "Lezioni Live",
    "Assista as transmissões em tempo real e mentorias com a comunidade.": "Guarda le trasmissioni in tempo reale e le sessioni di mentoring con la comunità.",
    "Carregando transmissões...": "Caricamento trasmissioni...",
    "Nenhuma aula ao vivo agendada": "Nessuna lezione live programmata",
    "As transmissões ao vivo com a Isabela Badini e mentorias da comunidade aparecerão aqui assim que forem programadas.": "Le trasmissioni live con Isabela Badini e i mentoring della comunità appariranno qui non appena saranno programmati.",
    "Ao Vivo Agora": "In Diretta Ora",
    "Encerrada (Gravação)": "Terminata (Registrazione)",
    "Nenhuma descrição disponível.": "Nessuna descrizione disponibile.",
    "Ferramentas de IA": "Strumenti IA",
    "Automatize seu estúdio com inteligência artificial treinada para tatuadores.": "Automatizza il tuo studio con un'intelligenza artificiale addestrata per i tatuatori.",
    "Seu mentor particular 24 horas por dia. Nossa IA sugere agulhas, pigmentos e ajuda no planejamento cirúrgico.": "Il tuo mentore privato 24 ore su 24. La nostra IA suggerisce aghi e pigmenti e aiuta nella pianificazione precisa delle tue sessioni.",
    "Bate-papo Interativo": "Chat Interattiva",
    "Avaliação de Trabalhos": "Valutazione dei Lavori",
    "Automatize seus orçamentos. A IA conversa com os clientes no WhatsApp, entende a ideia da tattoo e cadastra o cliente direto na sua agenda.": "Automatizza i tuoi preventivi. L'IA chatta con i clienti su WhatsApp, capisce l'idea del tatuaggio e registra il cliente direttamente nella tua agenda.",
    "Configurar Número": "Configura il Numero",
    "Integração de Agenda": "Integrazione Agenda",
    "Acessar WhatsApp": "Accedi a WhatsApp",
    "Matérias Disponíveis": "Corsi Disponibili",
    "Acesse seus treinamentos ou descubra novos conteúdos para evoluir sua arte.": "Accedi ai tuoi corsi o scopri nuovi contenuti per far evolvere la tua arte.",
    "Carregando acervo...": "Caricamento archivio...",
    "Nenhuma matéria disponível": "Nessun corso disponibile",
    "O administrador ainda não publicou nenhuma matéria.": "L'amministratore non ha ancora pubblicato nessun corso.",
    "Acessar": "Accedi",
    "Bloqueado": "Bloccato",
    "Módulos": "Moduli",
    "Desbloquear Matéria": "Sblocca Corso",
    "Acervo Oficial": "Archivio Ufficiale",
    "Biblioteca Pro": "Biblioteca Pro",
    "Baixe materiais práticos, e-books, manuais e guias estratégicos exclusivos.": "Scarica materiali pratici, e-book, manuali e guide strategiche esclusive.",
    "Todos": "Tutti",
    "Contratos": "Contratti",
    "Planilhas": "Fogli di Calcolo",
    "Outros": "Altri",
    "Nenhum material encontrado nesta categoria.": "Nessun materiale trovato in questa categoria.",
    "DOCUMENTO PDF": "DOCUMENTO PDF",
    "Acesso Liberado": "Accesso Sbloccato",
    "Baixar Documento PDF": "Scarica Documento PDF",
    "Manual prático com diretrizes e templates prontos.": "Manuale pratico con linee guida e modelli pronti.",
    "Guia Prático: Instagram + ChatGPT para Tatuadores": "Guida Pratica: Instagram + ChatGPT per Tatuatori",
    "Como utilizar Inteligência Artificial para gerar conteúdos de alto impacto, criar legendas persuasivas e atrair clientes diariamente no Instagram.": "Come utilizzare l'Intelligenza Artificiale per generare contenuti di grande impatto, creare didascalie persuasive e attirare clienti ogni giorno su Instagram.",
    "DOCUMENTO EXCLUSIVO PRO": "DOCUMENTO ESCLUSIVO PRO",
    "Gerencie sua conta, foto de perfil e informações de segurança.": "Gestisci il tuo account, la foto profilo e le informazioni di sicurezza.",
    "Nome atualizado com sucesso!": "Nome aggiornato con successo!",
    "Foto atualizada com sucesso!": "Foto aggiornata con successo!",
    "Salvar": "Salva",
    "Cancelar": "Annulla",
    "Editar Perfil": "Modifica Profilo",
    "Endereços de Email": "Indirizzi Email",
    "Verificado · Principal": "Verificato · Principale",
    "Segurança da Conta": "Sicurezza dell'Account",
    "Senha": "Password",
    "Gerencie a proteção do seu acesso": "Gestisci la protezione del tuo accesso",
    "Ativa": "Attiva",
    "Não configurada": "Non configurata",
    "Autenticação em Duas Etapas": "Autenticazione a Due Fattori",
    "Status de proteção da conta": "Stato di protezione dell'account",
    "Desativada": "Disattivata",
    "Usuário": "Utente",
    "Comunidade Authority": "Comunità Authority",
    "Compartilhe resultados, tire dúvidas e faça networking com outros artistas.": "Condividi risultati, fai domande e fai networking con altri artisti.",
    "Faça login para publicar": "Accedi per pubblicare",
    "Adicionar Foto": "Aggiungi Foto",
    "Enviando...": "Invio in corso...",
    "Publicar": "Pubblica",
    "Carregando feed...": "Caricamento feed...",
    "Nenhuma publicação ainda. Seja o primeiro a postar!": "Ancora nessun post. Sii il primo a pubblicare!",
    "Editar Publicação": "Modifica Post",
    "Apagar Publicação": "Elimina Post",
    "Salvando...": "Salvataggio...",
    "Curtidas": "Mi Piace",
    "Comentários": "Commenti",
    "Explorar a Plataforma": "Esplora la Piattaforma",
    "Assista transmissões e mentorias ao vivo com a comunidade.": "Guarda trasmissioni e mentoring dal vivo con la comunità.",
    "Compartilhe resultados e conecte-se com outros artistas.": "Condividi risultati e connettiti con altri artisti.",
    "Tutor IA e assistente de WhatsApp para automatizar seu estúdio.": "Tutor IA e assistente WhatsApp per automatizzare il tuo studio.",
    "Explore as matérias disponíveis e continue seus estudos.": "Esplora i corsi disponibili e continua i tuoi studi.",
    "Baixe materiais, e-books e guias exclusivos.": "Scarica materiali, e-book e guide esclusive.",
    "Gerencie sua conta e informações de segurança.": "Gestisci il tuo account e le informazioni di sicurezza."
  },
  ja: {
    "HOME": "ホーム",
    "CURSOS": "コース",
    "TOOLS": "ツール",
    "DASHBOARD": "ダッシュボード",
    "Entrar": "ログイン",
    "Acesso Antecipado": "早期アクセス",
    "Acesso antecipado": "早期アクセス",
    "Painel do Aluno": "受講生パネル",
    "Painel Admin": "管理者パネル",
    "Sair da conta": "ログアウト",
    "Pesquisar...": "検索...",
    "Minha Conta": "マイアカウント",
    "Voltar": "戻る",
    "Especialistas": "スペシャリスト",
    "Evolua sua arte com inteligência artificial. Nossa ferramenta foi treinada exclusivamente com técnicas avançadas de tatuagem.": "人工知能であなたのアートを進化させましょう。私たちのツールは高度なタトゥー技術のみで訓練されています。",
    "Mais Vendido": "人気No.1",
    "Tutor IA Especialista": "専門AIチューター",
    "Um mentor particular disponível 24h. Tire dúvidas técnicas em tempo real, receba sugestões precisas de agulhas e pigmentos para cada projeto, e tenha ajuda no planejamento completo das suas sessões.": "24時間利用可能な専属メンター。リアルタイムで技術的な疑問を解決し、プロジェクトごとに正確な針と顔料の提案を受け、セッションの計画を完全にサポートします。",
    "Planejamento de Sessão": "セッション計画",
    "Análise de Pigmentos": "顔料分析",
    "Mentoria Técnica 24h": "24時間技術メンタリング",
    "Gratuito": "無料",
    "Acessar Tutor": "チューターにアクセス",
    "Novo": "新機能",
    "Assistente WhatsApp": "WhatsAppアシスタント",
    "Automatize seus orçamentos. A IA conversa com os clientes no WhatsApp, entende a ideia da tattoo e já sugere valores baseados na sua tabela.": "見積もりを自動化。AIがWhatsAppで顧客と会話し、タトゥーのアイデアを理解して、あなたの料金表に基づいた価格を提案します。",
    "Orçamentos Automáticos": "自動見積もり",
    "Agendamento de Horários": "予約スケジュール管理",
    "Triagem de Clientes 24h": "24時間顧客スクリーニング",
    "/mês": "/月",
    "Assinar Assistente": "アシスタントに登録",
    "© 2026 Ink Authority. Todos os direitos reservados.": "© 2026 Ink Authority. 無断複製・転載を禁じます。",
    "Desenvolvido para criadores e tatuadores profissionais.": "プロのクリエイターとタトゥーアーティストのために開発。",
    "O Primeiro Passo Para o Topo": "頂点への第一歩",
    "Posicionamento para": "ポジショニング対象：",
    "tatuadores": "タトゥーアーティスト",
    "Não basta ser o melhor tatuador se ninguém conhece o seu trabalho. Aprenda os segredos exatos para se posicionar como autoridade, atrair clientes que pagam caro e transformar sua arte num negócio altamente lucrativo.": "誰もあなたの仕事を知らなければ、最高のタトゥーアーティストであるだけでは不十分です。権威として自分を位置づけ、高く支払う顧客を惹きつけ、あなたのアートを高収益なビジネスに変える正確な秘訣を学びましょう。",
    "O que é posicionamento e como aplicá-lo à sua carreira artística": "ポジショニングとは何か、それをアーティストとしてのキャリアにどう応用するか",
    "Estruturação das suas redes sociais": "SNSの構築方法",
    "Criação de conteúdos que atraem clientes": "顧客を惹きつけるコンテンツ制作",
    "Técnicas de vendas e conversão de clientes": "販売テクニックと顧客成約",
    "Como utilizar o tráfego pago de forma objetiva": "有料広告を効果的に活用する方法",
    "Acesso à comunidade exclusiva da Ink Authority": "Ink Authority限定コミュニティへのアクセス",
    "🎁 BÔNUS: Análise de perfil grátis (para os 20 primeiros)": "🎁 ボーナス：無料プロフィール診断（先着20名様）",
    "Investimento": "投資額",
    "Ou 12x de R$ 99,70": "または分割12回、各R$99.70",
    "Processando...": "処理中...",
    "Garantir Vaga": "席を確保する",
    "Acesso imediato após o pagamento": "支払い後すぐにアクセス可能",
    "Assista ao Vídeo": "動画を見る",
    "Aumente o som": "音量を上げてください",
    "Menu": "メニュー",
    "Meu Aprendizado": "マイラーニング",
    "Ao Vivo": "ライブ",
    "Comunidade": "コミュニティ",
    "Minhas Matérias": "マイコース",
    "Biblioteca": "ライブラリ",
    "Meu Perfil": "マイプロフィール",
    "Perfil": "プロフィール",
    "Bem-vindo de volta,": "おかえりなさい、",
    "Acompanhe seu progresso de aprendizado na Ink Authority.": "Ink Authorityでの学習の進捗を確認しましょう。",
    "Meu Aprendizado em Andamento": "進行中の学習",
    "Carregando seu progresso...": "進捗を読み込み中...",
    "Nenhum curso em andamento": "進行中のコースはありません",
    "Seu progresso de estudo aparecerá aqui conforme você acessar e concluir as aulas das matérias disponíveis.": "利用可能なコースのレッスンにアクセスして修了すると、ここに学習の進捗が表示されます。",
    "Explorar Matérias Disponíveis": "利用可能なコースを見る",
    "Curso da metodologia Ink Authority.": "Ink Authorityメソッドのコース。",
    "Continuar Estudando": "学習を続ける",
    "Aulas ao Vivo": "ライブ授業",
    "Assista as transmissões em tempo real e mentorias com a comunidade.": "リアルタイム配信やコミュニティとのメンタリングをご覧ください。",
    "Carregando transmissões...": "配信を読み込み中...",
    "Nenhuma aula ao vivo agendada": "予定されているライブ授業はありません",
    "As transmissões ao vivo com a Isabela Badini e mentorias da comunidade aparecerão aqui assim que forem programadas.": "Isabela Badiniとのライブ配信やコミュニティメンタリングは、予定が決まり次第ここに表示されます。",
    "Ao Vivo Agora": "現在ライブ配信中",
    "Encerrada (Gravação)": "終了済み(録画)",
    "Nenhuma descrição disponível.": "説明はありません。",
    "Ferramentas de IA": "AIツール",
    "Automatize seu estúdio com inteligência artificial treinada para tatuadores.": "タトゥーアーティスト向けに訓練された人工知能で、スタジオを自動化しましょう。",
    "Seu mentor particular 24 horas por dia. Nossa IA sugere agulhas, pigmentos e ajuda no planejamento cirúrgico.": "24時間対応の専属メンター。AIが針や顔料を提案し、施術の緻密な計画をサポートします。",
    "Bate-papo Interativo": "インタラクティブチャット",
    "Avaliação de Trabalhos": "作品評価",
    "Automatize seus orçamentos. A IA conversa com os clientes no WhatsApp, entende a ideia da tattoo e cadastra o cliente direto na sua agenda.": "見積もりを自動化しましょう。AIがWhatsAppでお客様とやり取りし、タトゥーのアイデアを理解して、直接スケジュールに登録します。",
    "Configurar Número": "番号を設定",
    "Integração de Agenda": "スケジュール連携",
    "Acessar WhatsApp": "WhatsAppを開く",
    "Matérias Disponíveis": "利用可能なコース",
    "Acesse seus treinamentos ou descubra novos conteúdos para evoluir sua arte.": "トレーニングにアクセスするか、新しいコンテンツであなたのアートを進化させましょう。",
    "Carregando acervo...": "コレクションを読み込み中...",
    "Nenhuma matéria disponível": "利用可能なコースはありません",
    "O administrador ainda não publicou nenhuma matéria.": "管理者はまだコースを公開していません。",
    "Acessar": "アクセス",
    "Bloqueado": "ロック中",
    "Módulos": "モジュール",
    "Desbloquear Matéria": "コースのロックを解除",
    "Acervo Oficial": "公式コレクション",
    "Biblioteca Pro": "プロライブラリ",
    "Baixe materiais práticos, e-books, manuais e guias estratégicos exclusivos.": "実践的な資料、電子書籍、マニュアル、限定戦略ガイドをダウンロードしましょう。",
    "Todos": "すべて",
    "Contratos": "契約書",
    "Planilhas": "表計算シート",
    "Outros": "その他",
    "Nenhum material encontrado nesta categoria.": "このカテゴリーには資料が見つかりません。",
    "DOCUMENTO PDF": "PDFドキュメント",
    "Acesso Liberado": "アクセス許可済み",
    "Baixar Documento PDF": "PDFドキュメントをダウンロード",
    "Manual prático com diretrizes e templates prontos.": "ガイドラインと既製テンプレート付きの実践マニュアル。",
    "Guia Prático: Instagram + ChatGPT para Tatuadores": "実践ガイド:タトゥーアーティストのためのInstagram + ChatGPT",
    "Como utilizar Inteligência Artificial para gerar conteúdos de alto impacto, criar legendas persuasivas e atrair clientes diariamente no Instagram.": "人工知能を活用してインパクトのあるコンテンツを作成し、説得力のあるキャプションを書き、Instagramで毎日新しい顧客を惹きつける方法。",
    "DOCUMENTO EXCLUSIVO PRO": "限定PROドキュメント",
    "Gerencie sua conta, foto de perfil e informações de segurança.": "アカウント、プロフィール写真、セキュリティ情報を管理しましょう。",
    "Nome atualizado com sucesso!": "名前が正常に更新されました!",
    "Foto atualizada com sucesso!": "写真が正常に更新されました!",
    "Salvar": "保存",
    "Cancelar": "キャンセル",
    "Editar Perfil": "プロフィールを編集",
    "Endereços de Email": "メールアドレス",
    "Verificado · Principal": "確認済み・メイン",
    "Segurança da Conta": "アカウントのセキュリティ",
    "Senha": "パスワード",
    "Gerencie a proteção do seu acesso": "アクセスの保護を管理しましょう",
    "Ativa": "有効",
    "Não configurada": "未設定",
    "Autenticação em Duas Etapas": "二段階認証",
    "Status de proteção da conta": "アカウント保護の状態",
    "Desativada": "無効",
    "Usuário": "ユーザー",
    "Comunidade Authority": "Authorityコミュニティ",
    "Compartilhe resultados, tire dúvidas e faça networking com outros artistas.": "成果を共有し、質問をし、他のアーティストとネットワーキングしましょう。",
    "Faça login para publicar": "投稿するにはログインしてください",
    "Adicionar Foto": "写真を追加",
    "Enviando...": "送信中...",
    "Publicar": "投稿する",
    "Carregando feed...": "フィードを読み込み中...",
    "Nenhuma publicação ainda. Seja o primeiro a postar!": "まだ投稿がありません。最初の投稿をしましょう!",
    "Editar Publicação": "投稿を編集",
    "Apagar Publicação": "投稿を削除",
    "Salvando...": "保存中...",
    "Curtidas": "いいね",
    "Comentários": "コメント",
    "Explorar a Plataforma": "プラットフォームを見る",
    "Assista transmissões e mentorias ao vivo com a comunidade.": "コミュニティとのライブ配信やメンタリングをご覧ください。",
    "Compartilhe resultados e conecte-se com outros artistas.": "成果を共有し、他のアーティストとつながりましょう。",
    "Tutor IA e assistente de WhatsApp para automatizar seu estúdio.": "AIチューターとWhatsAppアシスタントでスタジオを自動化。",
    "Explore as matérias disponíveis e continue seus estudos.": "利用可能なコースを見て、学習を続けましょう。",
    "Baixe materiais, e-books e guias exclusivos.": "限定資料、電子書籍、ガイドをダウンロード。",
    "Gerencie sua conta e informações de segurança.": "アカウントとセキュリティ情報を管理しましょう。"
  },
  ru: {
    "HOME": "ГЛАВНАЯ",
    "CURSOS": "КУРСЫ",
    "TOOLS": "ИНСТРУМЕНТЫ",
    "DASHBOARD": "ДАШБОРД",
    "Entrar": "Войти",
    "Acesso Antecipado": "Ранний Доступ",
    "Acesso antecipado": "Ранний доступ",
    "Painel do Aluno": "Кабинет ученика",
    "Painel Admin": "Панель админа",
    "Sair da conta": "Выйти",
    "Pesquisar...": "Поиск...",
    "Minha Conta": "Мой аккаунт",
    "Voltar": "Назад",
    "Especialistas": "Специалисты",
    "Evolua sua arte com inteligência artificial. Nossa ferramenta foi treinada exclusivamente com técnicas avançadas de tatuagem.": "Развивайте своё искусство с помощью искусственного интеллекта. Наш инструмент обучен исключительно на продвинутых техниках татуировки.",
    "Mais Vendido": "Хит продаж",
    "Tutor IA Especialista": "ИИ-наставник",
    "Um mentor particular disponível 24h. Tire dúvidas técnicas em tempo real, receba sugestões precisas de agulhas e pigmentos para cada projeto, e tenha ajuda no planejamento completo das suas sessões.": "Персональный наставник, доступный 24 часа в сутки. Получайте ответы на технические вопросы в реальном времени, точные рекомендации по иглам и пигментам для каждого проекта, а также помощь в полном планировании сеансов.",
    "Planejamento de Sessão": "Планирование сеанса",
    "Análise de Pigmentos": "Анализ пигментов",
    "Mentoria Técnica 24h": "Техническая поддержка 24/7",
    "Gratuito": "Бесплатно",
    "Acessar Tutor": "Открыть наставника",
    "Novo": "Новинка",
    "Assistente WhatsApp": "WhatsApp-ассистент",
    "Automatize seus orçamentos. A IA conversa com os clientes no WhatsApp, entende a ideia da tattoo e já sugere valores baseados na sua tabela.": "Автоматизируйте расчёт стоимости. ИИ общается с клиентами в WhatsApp, понимает идею татуировки и сразу предлагает цену на основе вашего прайса.",
    "Orçamentos Automáticos": "Автоматические расчёты",
    "Agendamento de Horários": "Запись на приём",
    "Triagem de Clientes 24h": "Отбор клиентов 24/7",
    "/mês": "/мес.",
    "Assinar Assistente": "Подключить ассистента",
    "© 2026 Ink Authority. Todos os direitos reservados.": "© 2026 Ink Authority. Все права защищены.",
    "Desenvolvido para criadores e tatuadores profissionais.": "Создано для профессиональных креаторов и тату-мастеров.",
    "O Primeiro Passo Para o Topo": "Первый шаг к вершине",
    "Posicionamento para": "Позиционирование для",
    "tatuadores": "тату-мастеров",
    "Não basta ser o melhor tatuador se ninguém conhece o seu trabalho. Aprenda os segredos exatos para se posicionar como autoridade, atrair clientes que pagam caro e transformar sua arte num negócio altamente lucrativo.": "Недостаточно быть лучшим тату-мастером, если никто не знает о вашей работе. Узнайте точные секреты, как позиционировать себя как авторитета, привлекать клиентов, готовых хорошо платить, и превратить своё искусство в высокодоходный бизнес.",
    "O que é posicionamento e como aplicá-lo à sua carreira artística": "Что такое позиционирование и как применить его в вашей творческой карьере",
    "Estruturação das suas redes sociais": "Структурирование ваших социальных сетей",
    "Criação de conteúdos que atraem clientes": "Создание контента, привлекающего клиентов",
    "Técnicas de vendas e conversão de clientes": "Техники продаж и конверсии клиентов",
    "Como utilizar o tráfego pago de forma objetiva": "Как эффективно использовать платный трафик",
    "Acesso à comunidade exclusiva da Ink Authority": "Доступ к эксклюзивному сообществу Ink Authority",
    "🎁 BÔNUS: Análise de perfil grátis (para os 20 primeiros)": "🎁 БОНУС: Бесплатный анализ профиля (для первых 20)",
    "Investimento": "Инвестиция",
    "Ou 12x de R$ 99,70": "Или 12 платежей по R$99,70",
    "Processando...": "Обработка...",
    "Garantir Vaga": "Забронировать место",
    "Acesso imediato após o pagamento": "Мгновенный доступ после оплаты",
    "Assista ao Vídeo": "Смотреть видео",
    "Aumente o som": "Включите звук",
    "Menu": "Меню",
    "Meu Aprendizado": "Моё обучение",
    "Ao Vivo": "Прямой эфир",
    "Comunidade": "Сообщество",
    "Minhas Matérias": "Мои курсы",
    "Biblioteca": "Библиотека",
    "Meu Perfil": "Мой профиль",
    "Perfil": "Профиль",
    "Bem-vindo de volta,": "С возвращением,",
    "Acompanhe seu progresso de aprendizado na Ink Authority.": "Следите за своим прогрессом обучения на Ink Authority.",
    "Meu Aprendizado em Andamento": "Текущее обучение",
    "Carregando seu progresso...": "Загрузка вашего прогресса...",
    "Nenhum curso em andamento": "Нет курсов в процессе",
    "Seu progresso de estudo aparecerá aqui conforme você acessar e concluir as aulas das matérias disponíveis.": "Ваш учебный прогресс появится здесь по мере доступа к урокам доступных курсов и их завершения.",
    "Explorar Matérias Disponíveis": "Просмотреть Доступные Курсы",
    "Curso da metodologia Ink Authority.": "Курс по методике Ink Authority.",
    "Continuar Estudando": "Продолжить Обучение",
    "Aulas ao Vivo": "Уроки в Прямом Эфире",
    "Assista as transmissões em tempo real e mentorias com a comunidade.": "Смотрите трансляции в реальном времени и менторские сессии с сообществом.",
    "Carregando transmissões...": "Загрузка трансляций...",
    "Nenhuma aula ao vivo agendada": "Нет запланированных прямых эфиров",
    "As transmissões ao vivo com a Isabela Badini e mentorias da comunidade aparecerão aqui assim que forem programadas.": "Прямые трансляции с Изабелой Бадини и менторские сессии сообщества появятся здесь, как только будут запланированы.",
    "Ao Vivo Agora": "Сейчас в Эфире",
    "Encerrada (Gravação)": "Завершено (Запись)",
    "Nenhuma descrição disponível.": "Описание недоступно.",
    "Ferramentas de IA": "Инструменты ИИ",
    "Automatize seu estúdio com inteligência artificial treinada para tatuadores.": "Автоматизируйте свою студию с помощью искусственного интеллекта, обученного для тату-мастеров.",
    "Seu mentor particular 24 horas por dia. Nossa IA sugere agulhas, pigmentos e ajuda no planejamento cirúrgico.": "Ваш личный наставник 24 часа в сутки. Наш ИИ подсказывает иглы и пигменты, а также помогает точно спланировать сеансы.",
    "Bate-papo Interativo": "Интерактивный чат",
    "Avaliação de Trabalhos": "Оценка работ",
    "Automatize seus orçamentos. A IA conversa com os clientes no WhatsApp, entende a ideia da tattoo e cadastra o cliente direto na sua agenda.": "Автоматизируйте расчёт стоимости. ИИ общается с клиентами в WhatsApp, понимает идею татуировки и сразу добавляет клиента в ваше расписание.",
    "Configurar Número": "Настроить Номер",
    "Integração de Agenda": "Интеграция с Расписанием",
    "Acessar WhatsApp": "Открыть WhatsApp",
    "Matérias Disponíveis": "Доступные Курсы",
    "Acesse seus treinamentos ou descubra novos conteúdos para evoluir sua arte.": "Получите доступ к своим курсам или откройте новый контент, чтобы развивать своё искусство.",
    "Carregando acervo...": "Загрузка коллекции...",
    "Nenhuma matéria disponível": "Нет доступных курсов",
    "O administrador ainda não publicou nenhuma matéria.": "Администратор ещё не опубликовал ни одного курса.",
    "Acessar": "Открыть",
    "Bloqueado": "Заблокировано",
    "Módulos": "Модули",
    "Desbloquear Matéria": "Разблокировать Курс",
    "Acervo Oficial": "Официальная Коллекция",
    "Biblioteca Pro": "Библиотека Pro",
    "Baixe materiais práticos, e-books, manuais e guias estratégicos exclusivos.": "Скачивайте практические материалы, электронные книги, руководства и эксклюзивные стратегические гайды.",
    "Todos": "Все",
    "Contratos": "Контракты",
    "Planilhas": "Таблицы",
    "Outros": "Другое",
    "Nenhum material encontrado nesta categoria.": "В этой категории материалов не найдено.",
    "DOCUMENTO PDF": "PDF-ДОКУМЕНТ",
    "Acesso Liberado": "Доступ Открыт",
    "Baixar Documento PDF": "Скачать PDF-документ",
    "Manual prático com diretrizes e templates prontos.": "Практическое руководство с рекомендациями и готовыми шаблонами.",
    "Guia Prático: Instagram + ChatGPT para Tatuadores": "Практическое Руководство: Instagram + ChatGPT для Тату-мастеров",
    "Como utilizar Inteligência Artificial para gerar conteúdos de alto impacto, criar legendas persuasivas e atrair clientes diariamente no Instagram.": "Как использовать искусственный интеллект для создания эффектного контента, убедительных подписей и ежедневного привлечения клиентов в Instagram.",
    "DOCUMENTO EXCLUSIVO PRO": "ЭКСКЛЮЗИВНЫЙ PRO-ДОКУМЕНТ",
    "Gerencie sua conta, foto de perfil e informações de segurança.": "Управляйте своим аккаунтом, фото профиля и данными безопасности.",
    "Nome atualizado com sucesso!": "Имя успешно обновлено!",
    "Foto atualizada com sucesso!": "Фото успешно обновлено!",
    "Salvar": "Сохранить",
    "Cancelar": "Отмена",
    "Editar Perfil": "Редактировать Профиль",
    "Endereços de Email": "Адреса Электронной Почты",
    "Verificado · Principal": "Подтверждён · Основной",
    "Segurança da Conta": "Безопасность Аккаунта",
    "Senha": "Пароль",
    "Gerencie a proteção do seu acesso": "Управляйте защитой своего доступа",
    "Ativa": "Активен",
    "Não configurada": "Не настроен",
    "Autenticação em Duas Etapas": "Двухфакторная Аутентификация",
    "Status de proteção da conta": "Статус защиты аккаунта",
    "Desativada": "Отключена",
    "Usuário": "Пользователь",
    "Comunidade Authority": "Сообщество Authority",
    "Compartilhe resultados, tire dúvidas e faça networking com outros artistas.": "Делитесь результатами, задавайте вопросы и общайтесь с другими мастерами.",
    "Faça login para publicar": "Войдите, чтобы опубликовать",
    "Adicionar Foto": "Добавить Фото",
    "Enviando...": "Отправка...",
    "Publicar": "Опубликовать",
    "Carregando feed...": "Загрузка ленты...",
    "Nenhuma publicação ainda. Seja o primeiro a postar!": "Пока нет публикаций. Станьте первым!",
    "Editar Publicação": "Редактировать Публикацию",
    "Apagar Publicação": "Удалить Публикацию",
    "Salvando...": "Сохранение...",
    "Curtidas": "Нравится",
    "Comentários": "Комментарии",
    "Explorar a Plataforma": "Изучить Платформу",
    "Assista transmissões e mentorias ao vivo com a comunidade.": "Смотрите прямые трансляции и менторские сессии с сообществом.",
    "Compartilhe resultados e conecte-se com outros artistas.": "Делитесь результатами и общайтесь с другими мастерами.",
    "Tutor IA e assistente de WhatsApp para automatizar seu estúdio.": "ИИ-наставник и WhatsApp-ассистент для автоматизации вашей студии.",
    "Explore as matérias disponíveis e continue seus estudos.": "Изучите доступные курсы и продолжите обучение.",
    "Baixe materiais, e-books e guias exclusivos.": "Скачивайте эксклюзивные материалы, книги и гайды.",
    "Gerencie sua conta e informações de segurança.": "Управляйте своим аккаунтом и данными безопасности."
  }
};

const reverseMap: Record<string, string> = {};
for (const lang in masterDict) {
  for (const pt in masterDict[lang]) {
    const val = masterDict[lang][pt];
    if (val && val !== pt) {
      reverseMap[val.toLowerCase()] = pt;
    }
  }
}

export function FloatingMenu() {
  const pathname = usePathname();
  const [theme, setTheme] = useState("dark");
  const [isTranslateOpen, setIsTranslateOpen] = useState(false);

  // The floating language/theme buttons only need to be visible on the
  // landing page and the dashboard home -- on every other screen they just
  // sit in the way (they were overlapping the sidebar's "Perfil" link on
  // /dashboard/profile, for example). The translation engine below keeps
  // running regardless of this: it's driven by an interval reading
  // localStorage, not by whether these buttons are on screen, so a
  // language chosen once still applies on every page.
  const showButtons = pathname === "/" || pathname === "/dashboard";

  const languages = [
    { code: "pt", name: "Português" },
    { code: "en", name: "English" },
    { code: "es", name: "Español" },
    { code: "fr", name: "Français" },
    { code: "de", name: "Deutsch" },
    { code: "it", name: "Italiano" },
    { code: "ja", name: "日本語" },
    { code: "ru", name: "Русский" }
  ];

  const translateParentDOM = (targetLang: string) => {
    if (typeof document === "undefined") return;
    const walk = (node: Node | null | undefined) => {
      if (!node) return;
      if (node.nodeType === 3) {
        const val = node.nodeValue;
        if (!val || !val.trim()) return;

        const anyNode = node as any;
        if (anyNode._parentOrig === undefined) {
          const norm = val.trim();
          const pt = reverseMap[norm.toLowerCase()];
          anyNode._parentOrig = pt ? val.replace(norm, pt) : val;
        }

        const orig = anyNode._parentOrig;
        let res = orig;
        if (targetLang && targetLang !== "pt" && masterDict[targetLang]) {
          const norm = orig.trim();
          if (masterDict[targetLang][norm]) {
            res = orig.replace(norm, masterDict[targetLang][norm]);
          }
        }

        if (res !== node.nodeValue) {
          node.nodeValue = res;
        }
      } else if (node.nodeType === 1) {
        const el = node as HTMLElement;
        if (el.tagName !== "SCRIPT" && el.tagName !== "STYLE" && !el.classList.contains("notranslate")) {
          // Snapshot into a plain array before recursing: this now walks
          // the whole page (not just <nav>), and React mutates the live
          // DOM as it renders — e.g. mid-navigation, when clicking a nav
          // link unmounts the old page and mounts the new one. Iterating
          // the live childNodes NodeList by index while React is adding or
          // removing children out from under it throws (walk() would get
          // called with an out-of-range/undefined entry); a static
          // snapshot can't shrink mid-loop.
          Array.from(node.childNodes).forEach(walk);
        }
      }
    };

    // Walk the whole page (not just <nav>) so public pages like /tools and
    // /courses get translated too. This never touches the landing page's
    // own content: an <iframe>'s child nodes are its element in the parent
    // document, not the document loaded inside it, so walk() can't cross
    // that boundary — that content has its own separate translation engine
    // (public/landing-i18n.js).
    try {
      if (document.body) walk(document.body);
    } catch (err) {
      // Best-effort UI polish — never let a translation pass take the app
      // down with it (e.g. if it races a route transition).
      console.error("translateParentDOM failed:", err);
    }
  };

  useEffect(() => {
    const savedTheme = localStorage.getItem("theme") || "dark";
    setTheme(savedTheme);
    applyTheme(savedTheme);

    const savedLang = localStorage.getItem("lang") || "pt";
    translateParentDOM(savedLang);
    syncLang(savedLang);

    const interval = setInterval(() => {
      const currentTheme = localStorage.getItem("theme") || "dark";
      const currentLang = localStorage.getItem("lang") || "pt";
      translateParentDOM(currentLang);
      const iframes = document.querySelectorAll('iframe');
      iframes.forEach(iframe => {
        if (iframe && iframe.contentWindow) {
          iframe.contentWindow.postMessage({ type: 'SET_THEME', theme: currentTheme }, '*');
          iframe.contentWindow.postMessage({ type: 'SET_LANG', lang: currentLang }, '*');
        }
      });
    }, 400);

    return () => clearInterval(interval);
  }, []);

  const applyTheme = (newTheme: string) => {
    const html = document.documentElement;
    if (newTheme === "light") {
      html.classList.remove("dark");
      html.classList.add("light");
      document.body.style.backgroundColor = "#f6f7f9";
      document.body.style.color = "#111116";
    } else {
      html.classList.remove("light");
      html.classList.add("dark");
      document.body.style.backgroundColor = "#050505";
      document.body.style.color = "#ffffff";
    }

    const iframes = document.querySelectorAll('iframe');
    iframes.forEach(iframe => {
      if (iframe && iframe.contentWindow) {
        iframe.contentWindow.postMessage({ type: 'SET_THEME', theme: newTheme }, '*');
      }
    });
  };

  const toggleTheme = () => {
    const newTheme = theme === "dark" ? "light" : "dark";
    setTheme(newTheme);
    localStorage.setItem("theme", newTheme);
    applyTheme(newTheme);
  };

  const syncLang = (langCode: string) => {
    translateParentDOM(langCode);
    const iframes = document.querySelectorAll('iframe');
    iframes.forEach(iframe => {
      if (iframe && iframe.contentWindow) {
        iframe.contentWindow.postMessage({ type: 'SET_LANG', lang: langCode }, '*');
      }
    });
  };

  const changeLanguage = (langCode: string) => {
    localStorage.setItem("lang", langCode);
    syncLang(langCode);
    setIsTranslateOpen(false);
  };

  if (!showButtons) return null;

  return (
    <div className="fixed bottom-6 left-6 z-[9999] flex flex-col gap-3 notranslate items-start">
      {isTranslateOpen && (
        <div className="bg-black/90 backdrop-blur-md border border-white/10 rounded-2xl p-2 flex flex-col gap-1 mb-2 shadow-2xl animate-in fade-in slide-in-from-bottom-4 text-white min-w-[140px]">
          {languages.map((lang) => (
            <button
              key={lang.code}
              onClick={() => changeLanguage(lang.code)}
              className="text-left px-4 py-2 hover:bg-white/10 rounded-xl text-sm font-medium transition-colors"
            >
              {lang.name}
            </button>
          ))}
        </div>
      )}
      
      <div className="flex gap-3">
        <button
          onClick={() => setIsTranslateOpen(!isTranslateOpen)}
          className="w-12 h-12 rounded-full glass border border-white/10 flex items-center justify-center hover:bg-white/10 transition-colors shadow-lg hover:scale-105 active:scale-95 bg-black/50 text-white"
          title="Mudar Idioma"
        >
          <Globe className="w-5 h-5" />
        </button>

        <button
          onClick={toggleTheme}
          className="w-12 h-12 rounded-full glass border border-white/10 flex items-center justify-center hover:bg-white/10 transition-colors shadow-lg hover:scale-105 active:scale-95 bg-black/50 text-white"
          title="Alternar Modo Claro/Escuro"
        >
          {theme === "dark" ? <Sun className="w-5 h-5 text-yellow-500" /> : <Moon className="w-5 h-5 text-blue-500" />}
        </button>
      </div>
    </div>
  );
}
